### ISSUE TITLE
Support for RPostgres connection

### ISSUE THREAD

**Issue by BernoGreyling** [mablab/rpostgis#18]
Hi,

Are there any plans to add support for a RPostgres connection as the package is more actively maintained and supports SSL connections from Windows? SSL connections from RPostgresql only work from Linux it seems.

**Comment by dnbucklin** [comment]
Hi @BernoGreyling,
I don't have much time to commit, and I'm not sure the amount of work required to fully support RPostgres. But to allow for development on this, I opened a new branch [feature_postgres](https://github.com/mablab/rpostgis/tree/feature_rpostgres), which could be installed with `devtools`:

```
devtools::install_github("mablab/rpostgis", "feature_rpostgres")
```

This will allow the RPostgres connection for rpostgis. Some functions may work as-is, but I know that several rpostgis functions will produces errors, due to specifics of that driver. If you'd like to test and log errors to this issue that could help move forward on this.

**Comment by BernoGreyling** [comment]
Hi @dnbucklin ,

Thanks! Will give it a go and report back

**Comment by dnbucklin** [comment]
eae1f09 Feature has been added, now on CRAN (v1.4.3). Please note that support for the driver is experimental. Data import/export tests were passing, though there are noticeable issues with import/export of time columns.
