### ISSUE TITLE
Read geometries from materialized views

### ISSUE THREAD

**Issue by cswingle** [mablab/rpostgis#6]
I think this is more of a feature request to add support for materialized views, unless I'm missing something about the `pgGetGeom()` or `dbReadDataFrame()` functions, which fail when I try to read a materialized view with this sort of error:

    Error in dbReadDataFrame(con, c("public", "properties")) : 
    Table public.properties not found.

Geometry columns from materialized views do appear in `pgListGeom()`.

Thanks!

**Comment by dnbucklin** [comment]
Hi @cswingle ,
I've updated the package to allow materialized views, the fix is on both `master` and `dev` branches. Install from `master` using:

    devtools::install_github("mablab/rpostgis")

The issue was due to an internal function not finding materialized views in the information_schema.tables catalog (which is apparently [by design](https://www.postgresql.org/message-id/flat/20141010225327.GP28859%40tamriel.snowman.net#20141010225327.GP28859@tamriel.snowman.net)).

**Comment by cswingle** [comment]
Thanks @dnbucklin, and for the context from the postgres mailing list.
